### ISSUE TITLE
大佬，提个意见

### ISSUE THREAD

**Issue by newcardriver** [Aaronzzx/YESPDF#2]
## 最下面那个可以往上面走走
![QQ图片20190915221003](https://user-images.githubusercontent.com/44741731/64922789-c69b1880-d805-11e9-864e-c9d4ce225125.jpg)

**Comment by aaronzzx** [comment]
下面那个是被挡住了吗

zgyy <notifications@github.com> 于 2019年9月15日周日 22:11写道：

**Comment by newcardriver** [comment]
是的大佬，下面显示不完整，应该是手机长屏的问题导致的，我用模拟器试过是没有问题的。但是不影响使用。

**Comment by aaronzzx** [comment]
我看看

**Comment by newcardriver** [comment]
不影响使用的，不影响使用的，大佬还是先开发主功能【滑稽】
